### ISSUE TITLE
Different font sizes in SP

### ISSUE THREAD

**Issue by jiyuujin** [jiyuujin/routine#3]

**Comment by jiyuujin** [comment]
Android11 (Pixel3a) では再現しないようで

**Comment by jiyuujin** [comment]
うーん。iOSでは再現するの

**Comment by jiyuujin** [comment]
やってみる価値はあるかも

```css
html {
  -webkit-text-size-adjust: 100%;
}
```
